In [153]:
import numpy as np
import importlib
import sys
sys.path.append('/Users/morton/PycharmProjects/psifr')

In [156]:
recalls = [24, 22, 18, 19, 5, 6, 4, 3]
list_length = 24
allowed = list(range(1, list_length + 1))

In [151]:
print(recalls)
print(allowed)

[24, 22, 18, 19, 5, 6, 4, 3]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [158]:
%%timeit
actual, possible = fr.list_lags(recalls, allowed)

48 µs ± 468 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
from itertools import tee
def pairwise(iterable):
    "s -> (s0,s1), (s1,s2), (s2, s3), ..."
    a, b = tee(iterable)
    next(b, None)
    return zip(a, b)

In [10]:
f_lag = np.subtract

In [14]:
np.subtract(24, 4)

20

In [52]:
for prev, curr in pairwise(recalls):
    print(prev, curr)

24 22
22 18
18 19
19 5
5 6
6 4
4 3


In [144]:
allowed = list(range(1, 25))
possible = []
actual = []
for prev, curr in pairwise(recalls):
    actual.append(curr - prev)
    allowed.remove(prev)
    possible.extend(np.subtract(allowed, prev))
    curr = prev

In [147]:
possible

[-23,
 -22,
 -21,
 -20,
 -19,
 -18,
 -17,
 -16,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 -21,
 -20,
 -19,
 -18,
 -17,
 -16,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 1,
 -17,
 -16,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 1,
 2,
 3,
 5,
 -18,
 -17,
 -16,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 1,
 2,
 4,
 -4,
 -3,
 -2,
 -1,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 15,
 16,
 18,
 -5,
 -4,
 -3,
 -2,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 14,
 15,
 17,
 -3,
 -2,
 -1,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 16,
 17,
 19]

In [103]:
full = np.zeros(47, dtype=int)
lags = np.arange(-23, 24)
lags

array([-23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11,
       -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23])

In [104]:
den_raw = np.bincount(np.hstack(possible) + 23)
den = full.copy()
den[:len(den_raw)] = den_raw

In [105]:
num_raw = np.bincount(np.array(actual) + 23)
num = full.copy()
num[:len(num_raw)] = num_raw

In [106]:
#n = np.hstack(possible)
print(actual)
print(np.bincount(np.array(actual) + 23))
#np.bincount([6, 7, 8])

[-2, -4, 1, -14, 1, -2, -1]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 2 1 0 2]


In [107]:
np.vstack((num, lags))

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   1,   0,   2,   1,   0,   2,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0],
       [-23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11,
        -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23]])

In [118]:
np.divide?

Call signature:  np.divide(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'true_divide'>
File:            //anaconda3/envs/cfr/lib/python3.8/site-packages/numpy/__init__.py
Docstring:      
true_divide(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Returns a true division of the inputs, element-wise.

Instead of the Python traditional 'floor division', this returns a true
division.  True division adjusts the output type to present the best
answer, regardless of input types.

Parameters
----------
x1 : array_like
    Dividend array.
x2 : array_like
    Divisor array. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated arr

In [136]:
nonzero = den != 0

dtype('bool')

In [141]:
np.divide(num, den, out=np.empty(num.shape, dtype='float').fill(np.nan), where=nonzero)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.25      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16666667,
       0.        , 0.28571429, 0.2       ,        nan, 0.4       ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ,        nan,        nan,
              nan,        nan])

In [137]:
np.divide(num, den, out=np.zeros_like(num), where=den != 0)

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [111]:
import numpy.ma as ma
denma = ma.masked_array(den, den != 0)
np.divide(num, denma)

<ipython-input-111-d75b1a87a8ca>:3: RuntimeWarning: invalid value encountered in true_divide
  np.divide(num, denma)


masked_array(data=[--, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --, --],
             mask=[ True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True],
       fill_value=1e+20,
            dtype=float64)

In [44]:
n = np.bincount(np.array(possible) + 23)
n

array([1, 1, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 6, 7, 7,
       5, 1, 5, 5, 4, 4, 5, 4, 3, 3, 3, 3, 3, 2, 1, 1, 2, 2, 2, 2, 2, 1])

In [40]:
lags = np.arange(-23, 24)
lags[23]

0

In [27]:
actual

[-2, -4, 1, -14, 1, -2, -1]